//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Markuse_asjade_juurutamise_tööriist.Properties {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Markuse_asjade_juurutamise_tööriist.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static byte[] cpuid_darwin {
            get {
                object obj = ResourceManager.GetObject("cpuid_darwin", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] cpuid_linux {
            get {
                object obj = ResourceManager.GetObject("cpuid_linux", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] cpuid_win32 {
            get {
                object obj = ResourceManager.GetObject("cpuid_win32", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] verifile2 {
            get {
                object obj = ResourceManager.GetObject("verifile2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] secdata_enc {
            get {
                object obj = ResourceManager.GetObject("secdata_enc", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] tree {
            get {
                object obj = ResourceManager.GetObject("tree", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
